const launderers = [
  {
    id: 1,
    name: "Serjio Marquina",
    alias: "Professor",
    occupation: "Heist Planner",
    age:45,
    amount_laundered: 800000000,
    image: "https://wallpapercave.com/wp/wp5988791.jpg",
  },
  {
    id: 2,
    name: "Andres de Fonollosa",
    alias: "Berlin",
    occupation: "Robber",
    age:55,
    amount_laundered: 1000000000,
    image: "https://wallpapercave.com/wp/wp5475153.jpg",
  },
  {
    id: 3,
    name: "Silene Oliveira",
    alias: "Tokyo",
    occupation: "Robber",
    age:39,
    amount_laundered: 300000000,
    image: "https://wallpapercave.com/wp/wp8638125.jpg",
  },
  {
    id: 4,
    name: "Agata Jimenez",
    alias: "Nairobi",
    occupation: "Robber",
    age:40,
    amount_laundered: 1200000000,
    image: "https://wallpapercave.com/wp/wp5162352.jpg",
  },
  {
    id: 5,
    name: "Raquel Murillo Fuentes",
    alias: "Lisbon",
    occupation: "Police, Robber",
    age:45,
    amount_laundered: 600000000,
    image:"https://upload.wikimedia.org/wikipedia/en/9/9f/Raquel_Murillo.jpg",
  },
  {
    id: 6,
    name: "Daniel Ramos",
    alias: "Denver",
    occupation: "Robber",
    age:35,
    amount_laundered: 8000000,
    image: "https://wallpapercave.com/wp/wp6081631.jpg",
  },
  {
    id: 7,
    name: "Anibal Cortes",
    alias: "Rio",
    occupation: "Robber",
    age:28,
    amount_laundered: 100000000,
    image: "https://clusterchannel.com/wp-content/uploads/2021/05/Rio.jpg",
  },
  {
    id: 12,
    name: "Martin Berrote",
    alias: "Palermo",
    occupation: "Robber",
    age:45,
    amount_laundered:4500000,
    image: "https://wallpaperaccess.com/full/2703615.jpg",
  },
  {
    id: 9,
    name: "Mirko Dragic",
    alias: "Helsinki",
    occupation: "Robber",
    age:75,
    amount_laundered: 1000000,
    image:"https://www.pixel4k.com/wp-content/uploads/2020/01/helsinki-in-money-heist_1578252282.jpg",
  },
];